version: '3.9'

services:

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"

  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}-master"
    image: "citusdata/citus"
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "password"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"

  worker:
    image: "citusdata/citus"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}-manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    environment: *AUTH

volumes:
  healthcheck-volume:
