spring:
  application:
    name: dialogs
  data:
    redis:
      port: 16379

#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
#  flyway:
#    baseline-on-migrate: true
#    baseline-version: 1

logging:
  level:
    root: info
#    ru.smax: debug

server:
  port: 8081

management:
  tracing:
    sampling:
      probability: 1.0
